apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

images:
  - name: ghcr.io/chrisbotina7823/service-discovery
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/cloud-config
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/api-gateway
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/proxy-client
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/user-service
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/product-service
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/favourite-service
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/order-service
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/payment-service
    newTag: dev-latest
  - name: ghcr.io/chrisbotina7823/shipping-service
    newTag: dev-latest
