apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-discovery.yaml
  - cloud-config.yaml
  - zipkin.yaml
  - api-gateway.yaml
  - proxy-client.yaml
  - user-service.yaml
  - product-service.yaml
  - favourite-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - shipping-service.yaml
