---
# Expose Grafana via NodePort (accessible via <NODE_IP>:30300)
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30300  # Accessible via http://<NODE_IP>:30300
      protocol: TCP
---
# Expose Prometheus via NodePort (accessible via <NODE_IP>:30900)
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: observability
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30900  # Accessible via http://<NODE_IP>:30900
      protocol: TCP
