apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      initContainers:
      - name: wait-for-service-discovery
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z service-discovery 8761; do echo waiting for service-discovery; sleep 2; done']
      containers:
      - name: app
        image: ghcr.io/chrisbotina7823/proxy-client:latest
        ports:
        - containerPort: 8900
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_ZIPKIN_BASE-URL
          value: "http://zipkin:9411"
        - name: EUREKA_CLIENT_REGION
          value: "default"
        - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
          value: "myzone"
        - name: EUREKA_CLIENT_SERVICEURL_MYZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296/"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "proxy-client"
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          value: "8900"
        resources:
          limits:
            memory: 512Mi
            cpu: 300m
          requests:
            memory: 256Mi
            cpu: 150m
        livenessProbe:
          httpGet:
            path: /app/actuator/health
            port: 8900
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /app/actuator/health
            port: 8900
          initialDelaySeconds: 240
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
    prometheus: enabled
    context-path: "custom"
spec:
  type: ClusterIP
  selector:
    app: proxy-client
  ports:
  - name: http
    port: 8900
    targetPort: 8900
