{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (index .Values.global.imagePullSecrets 0).name }}
  namespace: {{ .Values.global.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ""
{{- end }}
