{{- range $key, $service := .Values.services }}
{{- if and $service.enabled $service.healthCheck.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $service.name }}-monitor
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $service.name }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ $service.name }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
{{- end }}
{{- end }}
