apiVersion: v2
name: ecommerce-microservices
description: Helm chart for ecommerce microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - microservices
  - ecommerce
  - spring-boot
maintainers:
  - name: ChrisBotina7823
