all:
  children:
    jenkins:
      hosts:
        jenkins-vm:
          ansible_host: "{{ lookup('env', 'JENKINS_VM_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/vm_key
          ansible_python_interpreter: /usr/bin/python3
      vars:
        jenkins_deploy_path: /opt/jenkins
        jenkins_source_path: "{{ playbook_dir }}/../jenkins"
